name: Build & Commit Books

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

permissions:
  contents: write

concurrency:
  group: build-books-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'   # no cache => no lockfile required

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: none

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-chromium

      - name: Ensure scripts are executable
        run: |
          chmod +x ./scripts/install.sh || true
          chmod +x ./scripts/build.en.sh || true
          chmod +x ./scripts/build.vi.sh || true

      - name: Install OS packages required by Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates fonts-noto fonts-noto-cjk fonts-noto-color-emoji \
            libasound2 libatk-bridge2.0-0 libatk1.0-0 libcairo2 libcups2 \
            libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 \
            libpango-1.0-0 libx11-6 libx11-xcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
            libxss1 libxtst6 lsb-release xdg-utils wget unzip

      - name: Put npm global bin on PATH
        run: |
          mkdir -p ~/.npm-global
          npm config set prefix ~/.npm-global
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      - name: Install toolchain (Asciidoctor + Mermaid + Chromium)
        run: |
          gem install --no-document asciidoctor asciidoctor-pdf asciidoctor-epub3 asciidoctor-diagram
          npm i -g @mermaid-js/mermaid-cli
          npx --yes @puppeteer/browsers install chromium@latest
          echo "PUPPETEER_EXECUTABLE_PATH=$(npx --yes @puppeteer/browsers path chromium)" >> $GITHUB_ENV

      - name: Build (English)
        run: ./scripts/build.en.sh production

      - name: Build (Vietnamese)
        run: ./scripts/build.vi.sh production

      - name: Prepare GitHub Pages index
        run: |
          test -f docs/en/book.html || { echo "docs/en/book.html not found"; exit 1; }
          cp -f docs/en/book.html docs/index.html
          cp -rf docs/en/images docs/images || true

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit changes (if any)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          SHORT_SHA=$(git rev-parse --short HEAD)
          TS=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          git commit -m "chore(docs): rebuild book outputs [skip ci] (${TS}, ${SHORT_SHA})"
          git push origin "HEAD:${BRANCH}"
