name: Build & Commit Books

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    # Avoid loop when we commit generated docs back
    paths-ignore:
      - 'docs/**'

permissions:
  contents: write

concurrency:
  group: build-books-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure scripts are executable
        run: |
          chmod +x ./scripts/install.sh || true
          chmod +x ./scripts/build.en.sh || true
          chmod +x ./scripts/build.vi.sh || true

      - name: Install dependencies
        run: ./scripts/install.sh

      - name: Build (English)
        run: ./scripts/build.en.sh

      - name: Build (Vietnamese)
        run: ./scripts/build.vi.sh

      - name: Prepare GitHub Pages index
        run: |
          test -f docs/en/book.html || { echo "docs/en/book.html not found"; exit 1; }
          cp -f docs/en/book.html docs/index.html

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit changes (if any)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          SHORT_SHA=$(git rev-parse --short HEAD)
          TS=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          git commit -m "chore(docs): rebuild book outputs [skip ci] (${TS}, ${SHORT_SHA})"
          git push origin "HEAD:${BRANCH}"
