name: Build & Commit Books

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

permissions:
  contents: write

concurrency:
  group: build-books-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (for any tooling you might add later)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: none

      # Optional caches to speed up runs
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: ~/.gem
          key: gem-${{ runner.os }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: |
            gem-${{ runner.os }}-

      - name: Ensure scripts are executable
        run: |
          chmod +x ./scripts/install.sh || true
          chmod +x ./scripts/build.en.sh || true
          chmod +x ./scripts/build.vi.sh || true

      - name: Install Asciidoctor toolchain (Kroki)
        run: |
          gem install --no-document \
            asciidoctor asciidoctor-pdf asciidoctor-epub3 \
            asciidoctor-diagram asciidoctor-kroki rouge

      # If your build scripts need npm for anything else later:
      - name: Prepare npm global bin on PATH (optional)
        run: |
          mkdir -p ~/.npm-global
          npm config set prefix ~/.npm-global
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      # Build English (no Chrome needed)
      - name: Build (English)
        run: ./scripts/build.en.sh production

      # Build Vietnamese
      - name: Build (Vietnamese)
        run: ./scripts/build.vi.sh production

      - name: Prepare GitHub Pages index
        run: |
          test -f docs/en/book.html || { echo "docs/en/book.html not found"; exit 1; }
          cp -f docs/en/book.html docs/index.html
          cp -rf docs/en/images docs/images || true

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit changes (if any)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          SHORT_SHA=$(git rev-parse --short HEAD)
          TS=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          git commit -m "chore(docs): rebuild book outputs [skip ci] (${TS}, ${SHORT_SHA})"
          git push origin "HEAD:${BRANCH}"
